#!/nix/store/r5sxfcwq9324xvcd1z312kb9kkddqvld-bash-4.3-p30/bin/sh  
#
# print the subject
#

for i in $*
do
	n=`openssl x509 -subject -issuer -enddate -noout -in $i`
	echo "$i"
	echo "$n"
	echo "--------"
done
